// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtlpMi0PGEBQqF9pxlXG2zwoKAJVsaIU',
    appId: '1:29752095109:web:d12dfafa44a4a81dca94ec',
    messagingSenderId: '29752095109',
    projectId: 'lawrental',
    authDomain: 'lawrental.firebaseapp.com',
    storageBucket: 'lawrental.appspot.com',
    measurementId: 'G-BYVF0R5N2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCls-nryeyJkiR414tIFQfUmlJA4JbdC10',
    appId: '1:29752095109:android:c3ab85029c173c5dca94ec',
    messagingSenderId: '29752095109',
    projectId: 'lawrental',
    storageBucket: 'lawrental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTtMNQMDFz7p3u28-JxPSlFmkLUV-Gl8',
    appId: '1:29752095109:ios:9e82ba08fa6d63c2ca94ec',
    messagingSenderId: '29752095109',
    projectId: 'lawrental',
    storageBucket: 'lawrental.appspot.com',
    iosBundleId: 'com.example.lawrental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTtMNQMDFz7p3u28-JxPSlFmkLUV-Gl8',
    appId: '1:29752095109:ios:9e82ba08fa6d63c2ca94ec',
    messagingSenderId: '29752095109',
    projectId: 'lawrental',
    storageBucket: 'lawrental.appspot.com',
    iosBundleId: 'com.example.lawrental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwtlpMi0PGEBQqF9pxlXG2zwoKAJVsaIU',
    appId: '1:29752095109:web:ef900f3a2f01a52bca94ec',
    messagingSenderId: '29752095109',
    projectId: 'lawrental',
    authDomain: 'lawrental.firebaseapp.com',
    storageBucket: 'lawrental.appspot.com',
    measurementId: 'G-WLVDQV87TN',
  );
}
